# Generated by Django 4.2.9 on 2025-07-28 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('email_1', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
