# Generated by Django 4.2.9 on 2025-07-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='email_1',
        ),
    ]
