# Generated by Django 4.2.9 on 2025-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_manager_email_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
