version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: resourceoptima
      POSTGRES_USER: resourceoptima
      POSTGRES_PASSWORD: resourceoptima
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  application:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      DATABASE_URL: postgres://resourceoptima:resourceoptima@db:5432/resourceoptima

volumes:
  postgres_data:
