# Generated by Django 4.2.9 on 2025-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_resource_manager'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='skill_required',
        ),
        migrations.AddField(
            model_name='task',
            name='skill_required',
            field=models.ManyToManyField(related_name='tasks', to='resource.skill'),
        ),
    ]
