# Generated by Django 4.2.9 on 2025-07-28 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_skill_name'),
        ('project', '0002_remove_task_skill_required_task_skill_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='resource.resource')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='project.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task',), name='unique_task_assignment'),
        ),
    ]
