# Generated by Django 4.2.9 on 2025-07-29 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_skill_name'),
        ('project', '0003_taskassignment_taskassignment_unique_task_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='availability',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment', to='resource.resourceavailability'),
            preserve_default=False,
        ),
    ]
