# Generated by Django 4.2.9 on 2025-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_taskassignment_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_resource_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('partial assigned', 'Partial Assigned'), ('not assigned', 'Not Assigned')], default='not assigned', max_length=20),
            preserve_default=False,
        ),
    ]
